# docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vikashpg
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=vibemeter_db
      - SECRET_KEY=your_secret_key_here_change_in_production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - EMAILS_FROM_NAME=Vibemeter Bot
    volumes:
      - ./app:/app/app
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vikashpg
      - POSTGRES_DB=vibemeter_db
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data: